//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CSDL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/TaiKhoan_wsv.asmx")]
        public string DoAn_CSDL_TaiKhoan_wsv_TaiKhoan_wsv {
            get {
                return ((string)(this["DoAn_CSDL_TaiKhoan_wsv_TaiKhoan_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/Menu_wsv.asmx")]
        public string DoAn_CSDL_Menu_wsv_Menu_wsv {
            get {
                return ((string)(this["DoAn_CSDL_Menu_wsv_Menu_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/PhanQuyen_wsv.asmx")]
        public string DoAn_CSDL_PhanQuyen_wsv_PhanQuyen_wsv {
            get {
                return ((string)(this["DoAn_CSDL_PhanQuyen_wsv_PhanQuyen_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/HeThong_wsv.asmx")]
        public string DoAn_CSDL_HeThong_wsv_HeThong_wsv {
            get {
                return ((string)(this["DoAn_CSDL_HeThong_wsv_HeThong_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/Kho_wsv.asmx")]
        public string DoAn_CSDL_Kho_wsv_Kho_wsv {
            get {
                return ((string)(this["DoAn_CSDL_Kho_wsv_Kho_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/ViTri_wsv.asmx")]
        public string DoAn_CSDL_ViTri_wsv_ViTri_wsv {
            get {
                return ((string)(this["DoAn_CSDL_ViTri_wsv_ViTri_wsv"]));
            }
        }
    }
}
