//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PublicAPI.Menu_wsv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Menu_wsvSoap", Namespace="http://tempuri.org/")]
    public partial class Menu_wsv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetListMenuOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Menu_wsv() {
            this.Url = global::PublicAPI.Properties.Settings.Default.PublicAPI_Menu_wsv_Menu_wsv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetListMenuCompletedEventHandler GetListMenuCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListMenu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public API_ResultOfListOfview_Menu GetListMenu(string loginCode) {
            object[] results = this.Invoke("GetListMenu", new object[] {
                        loginCode});
            return ((API_ResultOfListOfview_Menu)(results[0]));
        }
        
        /// <remarks/>
        public void GetListMenuAsync(string loginCode) {
            this.GetListMenuAsync(loginCode, null);
        }
        
        /// <remarks/>
        public void GetListMenuAsync(string loginCode, object userState) {
            if ((this.GetListMenuOperationCompleted == null)) {
                this.GetListMenuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListMenuOperationCompleted);
            }
            this.InvokeAsync("GetListMenu", new object[] {
                        loginCode}, this.GetListMenuOperationCompleted, userState);
        }
        
        private void OnGetListMenuOperationCompleted(object arg) {
            if ((this.GetListMenuCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListMenuCompleted(this, new GetListMenuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class API_ResultOfListOfview_Menu {
        
        private view_Menu[] dataField;
        
        private EnumErrCode errCodeField;
        
        private string errDesField;
        
        private int recordCountField;
        
        private int pageCountField;
        
        /// <remarks/>
        public view_Menu[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public EnumErrCode ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDes {
            get {
                return this.errDesField;
            }
            set {
                this.errDesField = value;
            }
        }
        
        /// <remarks/>
        public int RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class view_Menu {
        
        private int idField;
        
        private string iconField;
        
        private string titleField;
        
        private System.Nullable<int> reIDField;
        
        private string contentField;
        
        private string roleField;
        
        private int orderField;
        
        private System.Nullable<bool> activeField;
        
        private string linkField;
        
        private int phanQuyenField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Icon {
            get {
                return this.iconField;
            }
            set {
                this.iconField = value;
            }
        }
        
        /// <remarks/>
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> reID {
            get {
                return this.reIDField;
            }
            set {
                this.reIDField = value;
            }
        }
        
        /// <remarks/>
        public string Content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        public int Order {
            get {
                return this.orderField;
            }
            set {
                this.orderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string Link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
            }
        }
        
        /// <remarks/>
        public int PhanQuyen {
            get {
                return this.phanQuyenField;
            }
            set {
                this.phanQuyenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumErrCode {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Fail,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Empty,
        
        /// <remarks/>
        NotYetLogin,
        
        /// <remarks/>
        ExistMultiOfUnique,
        
        /// <remarks/>
        DiffrentPass,
        
        /// <remarks/>
        AlreadyExist,
        
        /// <remarks/>
        InvalidEndDate,
        
        /// <remarks/>
        FailUploadImage,
        
        /// <remarks/>
        SuccessWithEmptyTokenFirebase,
        
        /// <remarks/>
        PermissionDenied,
        
        /// <remarks/>
        FailAddNotification,
        
        /// <remarks/>
        DoesNotExist,
        
        /// <remarks/>
        ValidateRequiment,
        
        /// <remarks/>
        SuccessWithFailSomething,
        
        /// <remarks/>
        NotHaveQuotaToRollback,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetListMenuCompletedEventHandler(object sender, GetListMenuCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListMenuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListMenuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public API_ResultOfListOfview_Menu Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((API_ResultOfListOfview_Menu)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591