//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublicAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/TaiKhoan_wsv.asmx")]
        public string PublicAPI_TaiKhoan_wsv_TaiKhoan_wsv {
            get {
                return ((string)(this["PublicAPI_TaiKhoan_wsv_TaiKhoan_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/HeThong_wsv.asmx")]
        public string PublicAPI_HeThong_wsv_HeThong_wsv {
            get {
                return ((string)(this["PublicAPI_HeThong_wsv_HeThong_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/Kho_wsv.asmx")]
        public string PublicAPI_Kho_wsv_Kho_wsv {
            get {
                return ((string)(this["PublicAPI_Kho_wsv_Kho_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/ViTri_wsv.asmx")]
        public string PublicAPI_ViTri_wsv_ViTri_wsv {
            get {
                return ((string)(this["PublicAPI_ViTri_wsv_ViTri_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/Menu_wsv.asmx")]
        public string PublicAPI_Menu_wsv_Menu_wsv {
            get {
                return ((string)(this["PublicAPI_Menu_wsv_Menu_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/PhanQuyen_wsv.asmx")]
        public string PublicAPI_PhanQuyen_wsv_PhanQuyen_wsv {
            get {
                return ((string)(this["PublicAPI_PhanQuyen_wsv_PhanQuyen_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/LoaiMatHang_wsv.asmx")]
        public string PublicAPI_LoaiMatHang_wsv_LoaiMatHang_wsv {
            get {
                return ((string)(this["PublicAPI_LoaiMatHang_wsv_LoaiMatHang_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/NhaCungCap_wsv.asmx")]
        public string PublicAPI_NhaCungCap_wsv_NhaCungCap_wsv {
            get {
                return ((string)(this["PublicAPI_NhaCungCap_wsv_NhaCungCap_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/HopDong_wsv.asmx")]
        public string PublicAPI_HopDong_wsv_HopDong_wsv {
            get {
                return ((string)(this["PublicAPI_HopDong_wsv_HopDong_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/CuaHang_wsv.asmx")]
        public string PublicAPI_CuaHang_wsv_CuaHang_wsv {
            get {
                return ((string)(this["PublicAPI_CuaHang_wsv_CuaHang_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/PhieuXuat_wsv.asmx")]
        public string PublicAPI_PhieuXuat_PhieuXuat_wsv {
            get {
                return ((string)(this["PublicAPI_PhieuXuat_PhieuXuat_wsv"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://localhost:44377/View/MatHang_wsv.asmx")]
        public string PublicAPI_MatHang_wsv_MatHang_wsv {
            get {
                return ((string)(this["PublicAPI_MatHang_wsv_MatHang_wsv"]));
            }
        }
    }
}
