//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DoAn_CSDL.LoaiMatHang_wsv {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoaiMatHang_wsvSoap", Namespace="http://tempuri.org/")]
    public partial class LoaiMatHang_wsv : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsEmptyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListComboboxOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LoaiMatHang_wsv() {
            this.Url = global::DoAn_CSDL.Properties.Settings.Default.DoAn_CSDL_LoaiMatHang_wsv_LoaiMatHang_wsv;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IsEmptyCompletedEventHandler IsEmptyCompleted;
        
        /// <remarks/>
        public event GetListComboboxCompletedEventHandler GetListComboboxCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsEmpty", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public API_ResultOfBoolean IsEmpty() {
            object[] results = this.Invoke("IsEmpty", new object[0]);
            return ((API_ResultOfBoolean)(results[0]));
        }
        
        /// <remarks/>
        public void IsEmptyAsync() {
            this.IsEmptyAsync(null);
        }
        
        /// <remarks/>
        public void IsEmptyAsync(object userState) {
            if ((this.IsEmptyOperationCompleted == null)) {
                this.IsEmptyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsEmptyOperationCompleted);
            }
            this.InvokeAsync("IsEmpty", new object[0], this.IsEmptyOperationCompleted, userState);
        }
        
        private void OnIsEmptyOperationCompleted(object arg) {
            if ((this.IsEmptyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsEmptyCompleted(this, new IsEmptyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetListCombobox", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public API_ResultOfListOfListCombobox_ettOfInt32 GetListCombobox() {
            object[] results = this.Invoke("GetListCombobox", new object[0]);
            return ((API_ResultOfListOfListCombobox_ettOfInt32)(results[0]));
        }
        
        /// <remarks/>
        public void GetListComboboxAsync() {
            this.GetListComboboxAsync(null);
        }
        
        /// <remarks/>
        public void GetListComboboxAsync(object userState) {
            if ((this.GetListComboboxOperationCompleted == null)) {
                this.GetListComboboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListComboboxOperationCompleted);
            }
            this.InvokeAsync("GetListCombobox", new object[0], this.GetListComboboxOperationCompleted, userState);
        }
        
        private void OnGetListComboboxOperationCompleted(object arg) {
            if ((this.GetListComboboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListComboboxCompleted(this, new GetListComboboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class API_ResultOfBoolean {
        
        private bool dataField;
        
        private EnumErrCode errCodeField;
        
        private string errDesField;
        
        private int recordCountField;
        
        private int pageCountField;
        
        /// <remarks/>
        public bool Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public EnumErrCode ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDes {
            get {
                return this.errDesField;
            }
            set {
                this.errDesField = value;
            }
        }
        
        /// <remarks/>
        public int RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EnumErrCode {
        
        /// <remarks/>
        Error,
        
        /// <remarks/>
        Fail,
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        Empty,
        
        /// <remarks/>
        NotYetLogin,
        
        /// <remarks/>
        ExistMultiOfUnique,
        
        /// <remarks/>
        DiffrentPass,
        
        /// <remarks/>
        AlreadyExist,
        
        /// <remarks/>
        InvalidEndDate,
        
        /// <remarks/>
        FailUploadImage,
        
        /// <remarks/>
        SuccessWithEmptyTokenFirebase,
        
        /// <remarks/>
        PermissionDenied,
        
        /// <remarks/>
        FailAddNotification,
        
        /// <remarks/>
        DoesNotExist,
        
        /// <remarks/>
        ValidateRequiment,
        
        /// <remarks/>
        SuccessWithFailSomething,
        
        /// <remarks/>
        NotHaveQuotaToRollback,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListCombobox_ettOfInt32 {
        
        private int dataField;
        
        private string displayDataField;
        
        /// <remarks/>
        public int Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string DisplayData {
            get {
                return this.displayDataField;
            }
            set {
                this.displayDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class API_ResultOfListOfListCombobox_ettOfInt32 {
        
        private ListCombobox_ettOfInt32[] dataField;
        
        private EnumErrCode errCodeField;
        
        private string errDesField;
        
        private int recordCountField;
        
        private int pageCountField;
        
        /// <remarks/>
        public ListCombobox_ettOfInt32[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public EnumErrCode ErrCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrDes {
            get {
                return this.errDesField;
            }
            set {
                this.errDesField = value;
            }
        }
        
        /// <remarks/>
        public int RecordCount {
            get {
                return this.recordCountField;
            }
            set {
                this.recordCountField = value;
            }
        }
        
        /// <remarks/>
        public int PageCount {
            get {
                return this.pageCountField;
            }
            set {
                this.pageCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void IsEmptyCompletedEventHandler(object sender, IsEmptyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsEmptyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsEmptyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public API_ResultOfBoolean Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((API_ResultOfBoolean)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetListComboboxCompletedEventHandler(object sender, GetListComboboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListComboboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListComboboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public API_ResultOfListOfListCombobox_ettOfInt32 Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((API_ResultOfListOfListCombobox_ettOfInt32)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591